---
env:
  browser: true
  es6: true
extends: airbnb-typescript
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules: {}
